In [ ]:
import psycopg2

# Establish a connection to the database
conn = psycopg2.connect(
    database="test",
    user="root",
    password="Zyon-56241428",
    host="localhost",
    port=3306)

# Create a cursor object
cursor = conn.cursor()

# Execute a parameterized query
user_input = "Alice'; DROP TABLE users;"
query = "SELECT * FROM users WHERE username = %s"
cursor.execute(query, (user_input,))

# Fetch the results
results = cursor.fetchall()

# Close the cursor and connection
cursor.close()
conn.close()

In [4]:
import mysql.connector as connector
from pprint import pprint

DATABASE = "test"
HOST = "localhost"
USER = "root"
PASSWORD = "Zyon-56241428"

conn = connector.connect(
            database=DATABASE,
            host=HOST,
            user=USER,
            password=PASSWORD,
        )
i = ("7639a992-db4e-4f02-baa7-29c188444bf2",)
cursor = conn.cursor()
nid = "D1177531"
cursor.execute("""
             SELECT
                COUNT(gp.NID)
            FROM
                `group` as gp
            WHERE
                gp.GID = %s AND gp.ENABLE = 1 AND gp.NID LIKE "T%" """,
                (i[0],))

# cursor.execute("select * from project where NID = '%s'",("D1177531",))
results = cursor.fetchone()[0]
pprint(results)

cursor.close()
conn.close()

0

In [4]:
import re

nid = "D1177531"

re.match(r"^[dtDT]\d{7}$", nid)

In [4]:
a = """'
"
#
-
--
'%20--
--';
'%20;
=%20'
=%20;
=%20--
\x23
\x27
\x3D%20\x3B'
\x3D%20\x27
\x27\x4F\x52 SELECT *
\x27\x6F\x72 SELECT *
'or%20select *
admin'--
<>"'%;)(&+
'%20or%20''='
'%20or%20'x'='x
"%20or%20"x"="x
')%20or%20('x'='x
0 or 1=1
' or 0=0 --
" or 0=0 --
or 0=0 --
' or 0=0 #
" or 0=0 #
or 0=0 #
' or 1=1--
" or 1=1--
' or '1'='1'--
"' or 1 --'"
or 1=1--
or%201=1
or%201=1 --
' or 1=1 or ''='
" or 1=1 or ""="
' or a=a--
" or "a"="a
') or ('a'='a
") or ("a"="a
hi" or "a"="a
hi" or 1=1 --
hi' or 1=1 --
hi' or 'a'='a
hi') or ('a'='a
hi") or ("a"="a
'hi' or 'x'='x';
@variable
,@variable
PRINT
PRINT @@variable
select
insert
as
or
procedure
limit
order by
asc
desc
delete
update
distinct
having
truncate
replace
like
handler
bfilename
' or username like '%
' or uname like '%
' or userid like '%
' or uid like '%
' or user like '%
exec xp
exec sp
'; exec master..xp_cmdshell
'; exec xp_regread
t'exec master..xp_cmdshell 'nslookup www.google.com'--
--sp_password
\x27UNION SELECT
' UNION SELECT
' UNION ALL SELECT
' or (EXISTS)
' (select top 1
'||UTL_HTTP.REQUEST
1;SELECT%20*
to_timestamp_tz
tz_offset
&lt;&gt;&quot;'%;)(&amp;+
'%20or%201=1
%27%20or%201=1
%20$(sleep%2050)
%20'sleep%2050'
char%4039%41%2b%40SELECT
&apos;%20OR
'sqlattempt1
(sqlattempt2)
|
%7C
*|
%2A%7C
*(|(mail=*))
%2A%28%7C%28mail%3D%2A%29%29
*(|(objectclass=*))
%2A%28%7C%28objectclass%3D%2A%29%29
(
%28
)
%29
&
%26
!
%21
' or 1=1 or ''='
' or ''='
x' or 1=1 or 'x'='y
/
//
//*
*/*"""

a.split("\n")

["'",
 '"',
 '#',
 '-',
 '--',
 "'%20--",
 "--';",
 "'%20;",
 "=%20'",
 '=%20;',
 '=%20--',
 '#',
 "'",
 "=%20;'",
 "=%20'",
 "'OR SELECT *",
 "'or SELECT *",
 "'or%20select *",
 "admin'--",
 '<>"\'%;)(&+',
 "'%20or%20''='",
 "'%20or%20'x'='x",
 '"%20or%20"x"="x',
 "')%20or%20('x'='x",
 '0 or 1=1',
 "' or 0=0 --",
 '" or 0=0 --',
 'or 0=0 --',
 "' or 0=0 #",
 '" or 0=0 #',
 'or 0=0 #',
 "' or 1=1--",
 '" or 1=1--',
 "' or '1'='1'--",
 '"\' or 1 --\'"',
 'or 1=1--',
 'or%201=1',
 'or%201=1 --',
 "' or 1=1 or ''='",
 '" or 1=1 or ""="',
 "' or a=a--",
 '" or "a"="a',
 "') or ('a'='a",
 '") or ("a"="a',
 'hi" or "a"="a',
 'hi" or 1=1 --',
 "hi' or 1=1 --",
 "hi' or 'a'='a",
 "hi') or ('a'='a",
 'hi") or ("a"="a',
 "'hi' or 'x'='x';",
 '@variable',
 ',@variable',
 'PRINT',
 'PRINT @@variable',
 'select',
 'insert',
 'as',
 'or',
 'procedure',
 'limit',
 'order by',
 'asc',
 'desc',
 'delete',
 'update',
 'distinct',
 'having',
 'truncate',
 'replace',
 'like',
 'handler',
 'bfilename',
 "' or username like '%",
 "' or uname like '%",
 "' or userid like '%",
 "' or uid like '%",
 "' or user like '%",
 'exec xp',
 'exec sp',
 "'; exec master..xp_cmdshell",
 "'; exec xp_regread",
 "t'exec master..xp_cmdshell 'nslookup www.google.com'--",
 '--sp_password',
 "'UNION SELECT",
 "' UNION SELECT",
 "' UNION ALL SELECT",
 "' or (EXISTS)",
 "' (select top 1",
 "'||UTL_HTTP.REQUEST",
 '1;SELECT%20*',
 'to_timestamp_tz',
 'tz_offset',
 "&lt;&gt;&quot;'%;)(&amp;+",
 "'%20or%201=1",
 '%27%20or%201=1',
 '%20$(sleep%2050)',
 "%20'sleep%2050'",
 'char%4039%41%2b%40SELECT',
 '&apos;%20OR',
 "'sqlattempt1",
 '(sqlattempt2)',
 '|',
 '%7C',
 '*|',
 '%2A%7C',
 '*(|(mail=*))',
 '%2A%28%7C%28mail%3D%2A%29%29',
 '*(|(objectclass=*))',
 '%2A%28%7C%28objectclass%3D%2A%29%29',
 '(',
 '%28',
 ')',
 '%29',
 '&',
 '%26',
 '!',
 '%21',
 "' or 1=1 or ''='",
 "' or ''='",
 "x' or 1=1 or 'x'='y",
 '/',
 '//',
 '//*',
 '*/*']

In [1]:
import datetime

print(datetime.datetime.now)

<built-in method now of type object at 0x00007FFA100E25E0>

In [ ]:
import numpy as np

np.array

In [ ]:
if None:
    print("asd")
else:
    print("Das")